pipeline {
agent any
    environment {
        VAULT_ADDR="http://vault:8200"
        VAULT_TOKEN="${JENKINS_TOKEN}"
    }
    stages {     
        stage('Renew Token') {
        steps {
            sh '''
            set +x
            vault token renew
            '''
          }
      }
      stage('Clone Git Repo') {
          steps {
            sh """
            rm -rf demo-tfe-sentinel-aws
            git clone https://github.com/EchelonProject/demo-tfe-sentinel-aws
            """
          }
      } 
      stage('Get Temp TF Creds From Vault & Set') {
          steps {
              dir('demo-tfe-sentinel-aws') {
                sh '''
                set +x
                export ROLE_ID=$(vault read -field=role_id auth/approle/role/jenkins/role-id)
                export SECRET_ID=$(vault write -field=secret_id -f auth/approle/role/jenkins/secret-id)
                export VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id=$ROLE_ID secret_id=$SECRET_ID)
                export TF_TOKEN=$(VAULT_TOKEN=${VAULT_TOKEN} vault read -field=token terraform/creds/jenkins)
                rm -f ~/.terraformrc
                echo "credentials \\"app.terraform.io\\" {" >> ~/.terraformrc
                echo "token = \\"${TF_TOKEN}\\"" >> ~/.terraformrc
                echo "}" >> ~/.terraformrc
                '''
              }
          }
      }
      stage('TF Init') {
          steps {
              dir('demo-tfe-sentinel-aws') {
                sh '''
                terraform init -input=false
                '''
              }
          }
      }
      stage('TF Plan & Sentinel Policy Checks') {
          steps {
              dir('demo-tfe-sentinel-aws') {
                sh '''
                terraform plan -input=false
                '''
              }
          }
      }
      stage('TF Apply') {
          steps {
              dir('demo-tfe-sentinel-aws') {
                sh '''
                terraform apply --auto-approve
                '''
              }
          }
      }
    }
}